### ISSUE TITLE
Using custom pickone function

### ISSUE THREAD

**Issue by Froelund** [lucapasquale/insomnia-plugin-chance#4]
Currently I am unable to use the chancejs `pickone`. The interface fails to validate the options as valid JSON.

![image](https://user-images.githubusercontent.com/2089088/48402234-68a42d00-e72b-11e8-8fbb-17265064f6eb.png)

I believe it's related to the plugin wrapping the opts in `{}` when parsing.
https://github.com/lucapasquale/insomnia-plugin-chance/blob/master/index.js#L44

**Comment by lucapasquale** [comment]
Great catch! I've tried your PR but it seemed that it if I removed the `{ ... }` it would break when the arguments were not an array.

I've created a new branch that fixes that, and checks if the options are an array or just an object. I also added the `pickone` function, since it's really useful!

Thanks for the help

**Comment by Froelund** [comment]
Great! Thanks 👍
